<script lang="ts">
  import type { Snippet } from 'svelte'; import { Dialog as BitsDialog } from 'bits-ui'; import { Search, X } from '@lucide/svelte'; import { cn } from '../../internal/cn.js';
  export type CommandItem={id:string;label:string;description?:string;keywords?:string[];shortcut?:string;icon?:Snippet;disabled?:boolean;action?:()=>void};
  type Props={open?:boolean;items:CommandItem[];placeholder?:string;emptyLabel?:string;shortcut?:string;class?:string};
  let {open=$bindable(false),items,placeholder='Befehl oder Seite suchen …',emptyLabel='Keine passenden Befehle',shortcut='k',class:className}:Props=$props(); let query=$state('');
  let filtered=$derived(items.filter(item=>`${item.label} ${item.description??''} ${(item.keywords??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())));
  function select(item:CommandItem){if(item.disabled)return;item.action?.();open=false;query=''}
  function key(event:KeyboardEvent){if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()===shortcut.toLowerCase()){event.preventDefault();open=!open}if(event.key==='Escape')open=false}
</script>
<svelte:window onkeydown={key}/>
<BitsDialog.Root bind:open><BitsDialog.Portal><BitsDialog.Overlay class="rg-overlay"/><BitsDialog.Content class={cn('rg-dialog rg-command',className)} aria-label="Befehlspalette"><BitsDialog.Title class="rg-sr-only">Befehlspalette</BitsDialog.Title><BitsDialog.Description class="rg-sr-only">Durchsuche verfügbare Aktionen</BitsDialog.Description><div class="rg-command-search"><div class="rg-input-wrap"><Search size={17}/><input class="rg-input has-start" type="search" bind:value={query} {placeholder}/><button class="rg-input-action" type="button" aria-label="Schließen" onclick={()=>open=false}><X size={15}/></button></div></div><div class="rg-command-list">{#if filtered.length}{#each filtered as item}<button class="rg-command-item" type="button" disabled={item.disabled} onclick={()=>select(item)}><span style="display:flex;align-items:center;gap:.65rem">{#if item.icon}{@render item.icon()}{/if}<span><strong style="display:block">{item.label}</strong>{#if item.description}<small style="color:var(--rg-fg-muted)">{item.description}</small>{/if}</span></span>{#if item.shortcut}<kbd class="rg-kbd">{item.shortcut}</kbd>{/if}</button>{/each}{:else}<div class="rg-state" style="min-height:8rem;border:0">{emptyLabel}</div>{/if}</div></BitsDialog.Content></BitsDialog.Portal></BitsDialog.Root>
